vich_uploader:
  db_driver: orm

  mappings:
    posts:
      uri_prefix: /images/posts
      upload_destination: '%kernel.project_dir%/public/images/posts'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    products:
      uri_prefix: /images/products
      upload_destination: '%kernel.project_dir%/public/images/products'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
